on:
  push:
    branches:
      - "main"

jobs:
  build_deploy:
    runs-on: ubuntu-20.04
    name: "Build and Deploy"
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker build -t my-site .

      - name: Deploy
        run: echo "Deployed my awesome site"
